### ISSUE TITLE
permission to push

### ISSUE THREAD

**Issue by tylernstarr** [jbloomlab/SARS-CoV-2-RBD_MAP_LY-CoV555#1]
@jbloom -- I can't find this on the page somehow, but do I need to be added to have permission to push to this repo?

I did clone afresh after you had deleted and remade the repo. I was going to push a branch but am gettting a permission denied. Hope it's just that I need to be added, and not somethign wonky about the old vs new repo

**Comment by jbloom** [comment]
Just fixes
